spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/ddang?characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true #true : JPA 쿼리문 확인
server:
  servlet:
    session:
      timeout: 1800

jwt:
  header: Authorization
  secret: c3ByaW5nLWJvb3Qtc3ByaW5nTVZDLUpQQS1zcHJpbmctc2VjdXJpdHktd2l0aC1qd3QtcHJvamVjdC1hdWN0aW9u #'spring security project auction' base64로 encoding
  token-validity-in-seconds: 86400